name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # Use a matrix to test across different browsers
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        # Uncomment to test on multiple Node.js versions
        # node-version: [18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-browsers-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-browsers-
          
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Setup environment variables
      run: |
        echo "NEXT_PUBLIC_API_ENDPOINT=http://localhost:3000" >> $GITHUB_ENV
        echo "NODE_ENV=test" >> $GITHUB_ENV
        # Add other environment variables as needed
        # echo "DATABASE_URL=your_test_database_url" >> $GITHUB_ENV
        # echo "NEXTAUTH_SECRET=test_secret" >> $GITHUB_ENV
        # echo "NEXTAUTH_URL=http://localhost:3000" >> $GITHUB_ENV
        
    - name: Build the application
      run: npm run build
      
    - name: Start the application
      run: |
        npm run start &
        sleep 10  # Wait for the app to start
      env:
        PORT: 3000
        
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browser }}
      env:
        PLAYWRIGHT_HTML_REPORT: 1
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always() && !cancelled()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30
        
    - name: Upload screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure() && !cancelled()
      with:
        name: screenshots-${{ matrix.browser }}
        path: test-results/
        retention-days: 30

  # Optional: Add a separate job for linting
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
